-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 20:40:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema IBM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IBM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IBM` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `IBM` ;

-- -----------------------------------------------------
-- Table `IBM`.`employee_demographics_dimension_final`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`employee_demographics_dimension_final` (
  `EmployeeNumber` INT NOT NULL,
  `Age` INT NULL DEFAULT NULL,
  `DistanceFromHome` INT NULL DEFAULT NULL,
  `Gender` TEXT NULL DEFAULT NULL,
  `MaritalStatus` TEXT NULL DEFAULT NULL,
  `Attrition` TEXT NULL DEFAULT NULL,
  `BusinessTravel` TEXT NULL DEFAULT NULL,
  `WorkLifeBalance` INT NULL DEFAULT NULL,
  `JobInvolvement` INT NULL DEFAULT NULL,
  `OverTime` TEXT NULL DEFAULT NULL,
  `Education` INT NULL DEFAULT NULL,
  `EducationField` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`EmployeeNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `IBM`.`company_benefit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`company_benefit` (
  `EmployeeNumber` INT NULL DEFAULT NULL,
  `JobSatisfaction` INT NULL DEFAULT NULL,
  `RelationshipSatisfaction` INT NULL DEFAULT NULL,
  `StockOptionLevel` INT NULL DEFAULT NULL,
  `EnvironmentSatisfaction` INT NULL DEFAULT NULL,
  `employee_demographics_dimension_final_EmployeeNumber` INT NOT NULL,
  PRIMARY KEY (`employee_demographics_dimension_final_EmployeeNumber`),
  CONSTRAINT `fk_company_benefit_employee_demographics_dimension_final1`
    FOREIGN KEY (`employee_demographics_dimension_final_EmployeeNumber`)
    REFERENCES `IBM`.`employee_demographics_dimension_final` (`EmployeeNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `IBM`.`education_dimension_final`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`education_dimension_final` (
  `Education` INT NULL DEFAULT NULL,
  `EducationField` TEXT NULL DEFAULT NULL,
  `Education desc` TEXT NULL DEFAULT NULL,
  `employee_demographics_dimension_final_EmployeeNumber` INT NOT NULL,
  PRIMARY KEY (`employee_demographics_dimension_final_EmployeeNumber`),
  CONSTRAINT `fk_education_dimension_final_employee_demographics_dimension_1`
    FOREIGN KEY (`employee_demographics_dimension_final_EmployeeNumber`)
    REFERENCES `IBM`.`employee_demographics_dimension_final` (`EmployeeNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `IBM`.`jobrole_dimensions_final`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`jobrole_dimensions_final` (
  `JobLevel` INT NULL DEFAULT NULL,
  `JobRole` INT NULL DEFAULT NULL,
  `JobRole_desc` TEXT NULL DEFAULT NULL,
  `Department` TEXT NULL DEFAULT NULL,
  `employee_demographics_dimension_final_EmployeeNumber` INT NOT NULL,
  PRIMARY KEY (`employee_demographics_dimension_final_EmployeeNumber`),
  CONSTRAINT `fk_jobrole_dimensions_final_employee_demographics_dimension_f1`
    FOREIGN KEY (`employee_demographics_dimension_final_EmployeeNumber`)
    REFERENCES `IBM`.`employee_demographics_dimension_final` (`EmployeeNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `IBM`.`performance_job_`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`performance_job_` (
  `PercentSalaryHike` INT NULL DEFAULT NULL,
  `PerformanceRating` INT NULL DEFAULT NULL,
  `employee_demographics_dimension_final_EmployeeNumber` INT NOT NULL,
  PRIMARY KEY (`employee_demographics_dimension_final_EmployeeNumber`),
  CONSTRAINT `fk_performance_job__employee_demographics_dimension_final1`
    FOREIGN KEY (`employee_demographics_dimension_final_EmployeeNumber`)
    REFERENCES `IBM`.`employee_demographics_dimension_final` (`EmployeeNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `IBM`.`salary_employee_`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`salary_employee_` (
  `EmployeeNumber` INT NOT NULL,
  `PercentSalaryHike` INT NULL DEFAULT NULL,
  `HourlyRate` INT NULL DEFAULT NULL,
  `DailyRate` INT NULL DEFAULT NULL,
  `MonthlyRate` INT NULL DEFAULT NULL,
  `MonthlyIncome` INT NULL DEFAULT NULL,
  `employee_demographics_dimension_final_EmployeeNumber` INT NOT NULL,
  PRIMARY KEY (`EmployeeNumber`, `employee_demographics_dimension_final_EmployeeNumber`),
  INDEX `fk_salary_employee__employee_demographics_dimension_final1_idx` (`employee_demographics_dimension_final_EmployeeNumber` ASC) VISIBLE,
  CONSTRAINT `fk_salary_employee__employee_demographics_dimension_final1`
    FOREIGN KEY (`employee_demographics_dimension_final_EmployeeNumber`)
    REFERENCES `IBM`.`employee_demographics_dimension_final` (`EmployeeNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `IBM`.`work_history_dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`work_history_dimension` (
  `EmployeeNumber` INT NOT NULL,
  `NumCompaniesWorked` INT NULL DEFAULT NULL,
  `TotalWorkingYears` INT NULL DEFAULT NULL,
  `TrainingTimesLastYear` INT NULL DEFAULT NULL,
  `employee_demographics_dimension_final_EmployeeNumber` INT NOT NULL,
  PRIMARY KEY (`EmployeeNumber`, `employee_demographics_dimension_final_EmployeeNumber`),
  INDEX `fk_work_history_dimension_employee_demographics_dimension_f_idx` (`employee_demographics_dimension_final_EmployeeNumber` ASC) VISIBLE,
  CONSTRAINT `fk_work_history_dimension_employee_demographics_dimension_fin1`
    FOREIGN KEY (`employee_demographics_dimension_final_EmployeeNumber`)
    REFERENCES `IBM`.`employee_demographics_dimension_final` (`EmployeeNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `IBM`.`years_dimension_company_`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IBM`.`years_dimension_company_` (
  `EmployeeNumber` INT NULL DEFAULT NULL,
  `YearsAtCompany` INT NULL DEFAULT NULL,
  `YearsInCurrentRole` INT NULL DEFAULT NULL,
  `YearsSinceLastPromotion` INT NULL DEFAULT NULL,
  `YearsWithCurrManager` INT NULL DEFAULT NULL,
  `employee_demographics_dimension_final_EmployeeNumber` INT NOT NULL,
  `salary_employee__EmployeeNumber` INT NOT NULL,
  PRIMARY KEY (`employee_demographics_dimension_final_EmployeeNumber`, `salary_employee__EmployeeNumber`),
  INDEX `fk_years_dimension_company__salary_employee_1_idx` (`salary_employee__EmployeeNumber` ASC) VISIBLE,
  CONSTRAINT `fk_years_dimension_company__employee_demographics_dimension_f1`
    FOREIGN KEY (`employee_demographics_dimension_final_EmployeeNumber`)
    REFERENCES `IBM`.`employee_demographics_dimension_final` (`EmployeeNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_years_dimension_company__salary_employee_1`
    FOREIGN KEY (`salary_employee__EmployeeNumber`)
    REFERENCES `IBM`.`salary_employee_` (`EmployeeNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


select * from company_benefit;